ALTER TABLE TBL_USERS
ADD CONSTRAINT unique_email UNIQUE (EMAIL);

ALTER TABLE TBL_LOCATIONS
ADD CONSTRAINT unique_name UNIQUE (NOME);

ALTER TABLE TBL_ALERTS
ADD CONSTRAINT unique_type UNIQUE (TIPO_DESASTRE);